### PR TITLE
Updated to latest version of opcache-gui

### PR DESCRIPTION
**Pull request by amnuts**
Thanks for providing the opcache-gui as a Moodle plugin!  I did notice you were a number of versions behind, though.  I've just pushed a new version now which updates the CSS so that it should hopefully be less intrusive to the rest of the Moodle interface and not make quite as many style changes to the rest of the interface outside of the opcache-gui.  The latest version also includes some updated information you will not have in your current version, such as the optimisation levels not just being a number and an additional widget of info.

### CODE REVIEW

**Comment by abias** [comment]
Hey @amnuts ,

thank you very much for this PR and especially thank you for respecting the fact that your tool is embedded into Moodle with this plugin (as I have read on https://github.com/amnuts/opcache-gui/releases/tag/2.5.4 and on https://github.com/amnuts/opcache-gui/issues/47).

Unfortunately, I didn't have time to look at this plugin during the last months, but I am now more than grateful that you have prepared everything well for me!

This PR is now merged and I will publish a new version of this Moodle plugin soon.

Cheers,
Alex

**Comment by amnuts** [comment]
Hi @abias; thanks!  Last week I did update to a major new version of the gui which you may want to use instead of version 2.5.4?  https://github.com/amnuts/opcache-gui/releases/tag/3.0.0

I can submit another PR if you're like?

**Comment by amnuts** [comment]
Actually, I don't know for which version of PHP Moodle is intended and the newer version of the opcache-gui set it to 7.1 as a minimum, so maybe you cannot use version 3.0?

**Comment by abias** [comment]
Hey @amnuts ,

yes, I have seen that you have published a major update!

And while I have used your PR for another minor release of the plugin for Moodle 3.8, I have already used opcache-gui 3.0.0 for the major release of the plugin for Moodle 3.9!
And your PHP version requirement isn't a problem as Moodle 3.9 required PHP 7.2 at least.

BTW, you might be interested that the Moodle plugin is used, according to https://moodle.org/plugins/stats.php?plugin=tool_opcache, already on more than 1.100 sites worldwide!

Cheers,
Alex

**Comment by amnuts** [comment]
That's awesome @abias - great job on having your plugin so widely used!

**Pull request merged**
